import Head from "next/head";
import Image from "next/image";
import { About, Banner, Header } from "../components";
import Services from "../components/Services";
import { allBanks } from "../fakeData";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className="w-full">
			<Head>
				<title>BankPediaBD</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/logo.png"/>
			</Head>
			<main>
				<Banner />
				<About/>
				<Services/>
				<div className="container mx-auto">
					<h2 className="text-5xl font-bold text-center my-5"> Popular Banks</h2>
					<div className="flex flex-wrap gap-10">
						{allBanks.map((bank, index) => {
							return (
								<div key={index}>
									<Image
										src={bank.details.logo.src}
										height={bank.details.logo.height}
										width={bank.details.logo.width}
										alt="Bank Logo"
									/>
								</div>
							);
						})}
					</div>
				</div>
			</main>
		</div>
	);
}
